### ISSUE TITLE
Eslint or standard?

### ISSUE THREAD

**Issue by cloudiirain** [Shadowys/hako#17]
A quick suggestion that maybe we utilize code style conventions?

It's something worthwhile to establish if you're hoping to attract multiple contributors. If you intend to keep this on a smaller/more personal scale, then it's okay to do whatever you're most comfortable with.

A common thing to do is to use a linter. [ESLint](http://eslint.org/) is the most common one, though there are others. [Airbnb](https://github.com/airbnb/javascript) is a common javascript style guide that can be configured with eslintrc.

Another alternative is [feross/standard](https://github.com/feross/standard), which has an advantage in that it requires no configuration files and runs out of the box.

**Comment by Shadowys** [comment]
I like standardjs. It doesn't need additional configuration files.

**Comment by cloudiirain** [comment]
Do you have an opinion on semicolons? 

The strange thing about standardjs to me is that the recommended code style is no semicolons.

**Comment by Shadowys** [comment]
I think it's better to have none than have inconsistent semicolons. I don't mind either way, but its better to have consistency in style I guess.

I'm using Sublime Text3. How about you?

**Comment by Shadowys** [comment]
JavaScript inserts semicolons just fine unless you happen to have trailing brackets, AFAIK. I thought you would advocate the removal of semicolons because of python lol

**Comment by cloudiirain** [comment]
Webstorm. 

If we go with Standard, it's goodbye to semicolons. If we go with Eslint, we can keep the semicolons (if that's something that you prefer). It's really your decision here -- I can adapt to either.

I spent the summer programming with Meteor+React, using Eslint+Airbnb, so I've gotten used to the semicolons. q-q Also I started out with Java, so I'm more-or-less used to it. Python was something I randomly picked up. XD

**Comment by Shadowys** [comment]
I really like having no semicolons though.  (even though I find it weird at first... XD)

But it's mainly because there's no config file that I picked standardjs, so that's one less thing a dev would need to pickup.

**Comment by cloudiirain** [comment]
Got it! Let's say we're settled on standardjs! xD

**Comment by Shadowys** [comment]
This has been implemented in #21
