### ISSUE TITLE
API Resource Naming (separating URIs with different behavior)

### ISSUE THREAD

**Issue by cloudiirain** [Shadowys/hako#18]
Right now, the some URIs have multiple/different behaviors depending on what data is POST/GET sent. For instance, `/api/series` will create or update presumably based on whether the id is defined in the post data (id is optional on create?). It's more-or-less inferred from the POST data.

There's nothing really wrong with this, though I think it's a little bit more clear/intuitive if different behavior is separated into different URI endpoints. It's also easier to document when using apidocjs.

For instance, in the series model, we may want to support getting a **SeriesDetail** (detailed information on a particular series) and a **SeriesList** (getting a list of all series). In the conventional REST world, this is done with GET requests to different URIs:

```
GET /api/series/ --> SeriesList of all series
GET /api/series/<:series_id> --> SeriesDetail of a particular series
```
In GET, `?params` are typically reserved for optional formatting/filtering/modulating the returned data, not really for changing the logic of a API resource.

```
# As for creating vs. updating...

POST /api/series --> Create a new series
POST(PUT) /api/series/<:series_id> --> Update a particular series
```

It's really just an organizational thing... though if you have strong feelings about keeping it the way it is, that's fine too. OTL I'm just very used to REST API's that that tend to follow [this convention](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful):
```
GET /tickets - Retrieves a list of tickets
GET /tickets/12 - Retrieves a specific ticket
POST /tickets - Creates a new ticket
PUT /tickets/12 - Updates ticket #12
PATCH /tickets/12 - Partially updates ticket #12
DELETE /tickets/12 - Deletes ticket #12
```

**Comment by Shadowys** [comment]
Suggestion note to self or anyone to implement this without rewriting the code (both code to retrieve data is highly similar), merge req.query.params with postdata, while adding `/:id`, by using the extend module found in `./api/api/v0.2/index.js`, function `routeHandler`.

**Comment by Shadowys** [comment]
Resolved in [this commit](https://github.com/Shadowys/hako/commit/610c231b11150f1d0fad6eb98892c56c9985eabc)
