### ISSUE TITLE
Opening and closing mongoose connections

### ISSUE THREAD

**Issue by cloudiirain** [Shadowys/hako#24]
This is just a question (this is a subject I'm sure you know better than me), but why open and close the db connection on every method?

Most of the express4 tutorials ([like this one](http://adrianmejia.com/blog/2014/10/01/creating-a-restful-api-tutorial-with-nodejs-and-mongodb/)) that I've seen connect to the db when initializing the app and leave that connection open. 

Is there a reason why you like to open and close the connection a lot? XD

**Comment by Shadowys** [comment]
It's my OCD from my php days. I find not disconnecting from the db strange. 
It also leads to strange bugs when the GC have to closed the db and then you start a new call leading to clash in ports. Which is also the reason I call mongoose.disconnect() on every exit.

**Comment by Shadowys** [comment]
Leaving this here. I'll implement it when I've got the chance. Or @cloudiirain you could implement it if you have the time. GLHF for your exams too. Now I really have to sleep XD. 

https://gist.github.com/pasupulaphani/9463004

**Comment by cloudiirain** [comment]
Ah, I like the usage of the middleware. It's much cleaner, though it's really just syntax/organization anyways, and nothing to fuss too much over.

And thanks and goodnight!

**Comment by Shadowys** [comment]
All mongoose connections have been moved to the top level as per this commit:

https://github.com/Shadowys/hako/commit/0aeebe3a2a4a370d85eab06ba9416518f7724f5e

No mongoose connection will be made in the app now.
