### ISSUE TITLE
API v0.3 Volume Methods

### ISSUE THREAD

**Issue by Shadowys** [Shadowys/hako#29]
- [x] POST
- [x] GET
- [x] PUT
- [x] DELETE

**Comment by viggy96** [comment]
Just need to work on PUT request now.

**Comment by Shadowys** [comment]
The PUT and GET method (I'm adding a `populate` method) might still be in flux, but it shouldn't change much.

**Comment by Shadowys** [comment]
@viggy96 I think for volume/chapter/arc/pages method we should only use the ID as the reference as they wont have a unique title outside of the series they are residing in.
