### ISSUE TITLE
PUT Method requires non-null value to override and erase current values

### ISSUE THREAD

**Issue by Shadowys** [Shadowys/hako#30]
As the current PUT method removes null values, the client side may have to remove any current values by resetting them manually. Alternatively, the client can resend the whole data, but this may be inefficient.

**Comment by viggy96** [comment]
Might be able to solve this if variables that do not exist in the input object are actually undefined rather than null. Though someone needs to test what value is returned when a non-existent variable is requested from the input object.

**Comment by Shadowys** [comment]
Current behavior:
1. If the value is not in the input object, it is ignored.
2. If the value is in the input object, but has an empty value, it will be reverted to the array(`[]`), boolean (`false`) and number (`NaN`) equivalent
