### ISSUE TITLE
Versioning the api

### ISSUE THREAD

**Issue by cloudiirain** [Shadowys/hako#6]
A brief suggestion: [api versioning](http://broadcast.oreilly.com/2011/10/api-versioning.html)

Since we don't know how the api will change (especially after things go into production), we don't want to break any dependent front-end apps as we continue to develop/improve the backend (which will probably inevitably happen). The solution is to version the API.

For instance:
```
# Instead of this:
/api/project/view

# Support both of these:
/api/v1/project/view
/api/v2/project/view
```

There are multiple different strategies to version the API. Putting the version number in the URI is one idea, but there are other options too.

**Comment by cloudiirain** [comment]
I would have given this the suggestion label, but do we have that? ;-;

**Comment by Shadowys** [comment]
I think enhancement is fine.

Yeah I think we should version the api, but for the user we would primarily expose the most recent one.
For example:

`/api/project/view` is an alias to `/api/v3.4/project/view` where version 3.4 is the latest, but we also allow the user to specify `/api/v2/project/view` for the older version. 

This should probably be handled in the main api entry file.

**Comment by cloudiirain** [comment]
Either way is fine! I think it's best to be explicit though, because I'm assuming that programmers with less experience that may build on top of your API will just use the most obvious route (the alias, in other words). 

However, if you ever change the backend behavior of aliased route, any app that has that aliased route hard-coded in will break. The end-users will end up experiencing downtime because it might take days or more before the front-end developer can write a hotfix.

In my opinion, it's better practice to force the front-end developer to hard-code in a route version whose behavior will never change. This way, if we upgrade the backend, they can upgrade their front-end app on their own pace (and so that the changes don't hit them like a brick wall or cause apps to randomly break out of nowhere if the developer isn't available to make the hotfix).

**Comment by Shadowys** [comment]
That's a valid concern. I agree that hardcoding the route would free us from thinking too much about backward compability. 

Alright, so there would not be an alias for the api versions.
