### ISSUE TITLE
RESTful API?

### ISSUE THREAD

**Issue by cloudiirain** [Shadowys/hako#8]
Just a curiosity, but is there a reason why you chose to name your resources this way?
```
 /project/{update,delete,view}
 /section/{update,delete,view}
 /book/{update,delete,view}
 /chapter/{update,delete,view}
 /page/{create,view}
```

I'm personally very used to REST API's that that tend to follow [this convention](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful):
```
GET /tickets - Retrieves a list of tickets
GET /tickets/12 - Retrieves a specific ticket
POST /tickets - Creates a new ticket
PUT /tickets/12 - Updates ticket #12
PATCH /tickets/12 - Partially updates ticket #12
DELETE /tickets/12 - Deletes ticket #12
```

I mean, I'm not really sure what are the pros or cons of either method. I think most programmers tend to be more familiar with the latter style of naming REST resources. For instance, I know the twitter, wordpress, and most of the major API's generally follow this convention. [Some tutorials](https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4#express-router-and-routes) I saw for Express 4 also seem to lean towards the latter style.

If the former is something you already settled/decided on, never mind that I asked! XD I just brought it up in case you weren't aware of what's most commonly done.

**Comment by Shadowys** [comment]
I just wanted to get a quick feel of what the api should look like, so I just went for the POST instead, as I'm not sure what would be required for the API, but now that I've done it doesn't seem that I would need that much flexibility, so it's likely that I would reorganize it into:

/GET project <=this would accept a search query 
/POST project <=this would create or update a project based on the data given.
/DELETE project <=this would accept a unique name or id

**Comment by cloudiirain** [comment]
Cool cool~ I was just curious if there was a reason why you were going with mostly POST x3

**Comment by Shadowys** [comment]
Refer to the [api version 0.2 branch](https://github.com/Shadowys/hako/tree/apiv0.2) for current development.
